#!/usr/bin/env ruby
# SPDX-License-Identifier: MIT
# frozen_string_literal: true
#
# Generate src/eucjp-table.ts, the JIS X 0208 and JIS X 0212 halves of the
# in-tree EUC-JP encoder, from Ruby's own EUC-JP converter. Ruby implements
# the JIS mappings (U+301C WAVE DASH, U+2212 MINUS SIGN, U+00A2 CENT SIGN, ...)
# that iconv and Python use, unlike the WHATWG "euc-jp" tables browsers
# decode with, and it is also the tool build/compile-fixtures.sh uses to
# transcode the reference fixtures, so the encoder equals the fixture oracle
# by construction.
#
#   ruby scripts/gen-eucjp-table.rb          # rewrite src/eucjp-table.ts
#   ruby scripts/gen-eucjp-table.rb --check  # exit 1 if the committed file differs
#
# A cell is kept only when Ruby encodes the decoded character back to the same
# bytes, so characters reachable from more than one cell map the way Ruby's
# encoder maps them. Unassigned cells are "\0".

TARGET = File.expand_path('../src/eucjp-table.ts', __dir__)
UNASSIGNED = "\0"

def cell(bytes)
  text = bytes.pack('C*').force_encoding('EUC-JP').encode('UTF-8')
  return UNASSIGNED unless text.length == 1 && text.encode('EUC-JP').bytes == bytes

  text
rescue EncodingError
  UNASSIGNED
end

def plane(prefix)
  (0xA1..0xFE).map do |hi|
    (0xA1..0xFE).map { |lo| cell(prefix + [hi, lo]) }.join
  end
end

def literal(row)
  # Only "\0" and the delimiters need escaping; everything else is a printable
  # BMP character that TypeScript reads verbatim.
  escaped = row.gsub("\\") { '\\\\' }.gsub("'") { "\\'" }.gsub("\0") { '\\0' }
  "  '#{escaped}',"
end

# Sanity checks of the assumptions the encoder makes.
(0xA1..0xDF).each do |b|
  char = [0x8E, b].pack('C*').force_encoding('EUC-JP').encode('UTF-8')
  raise "half-width katakana 8E #{b.to_s(16)} != U+#{char.ord.to_s(16)}" unless char.ord == 0xFF61 + (b - 0xA1)
end
(0..0x7F).each do |b|
  raise "ASCII #{b} is not identity" unless [b].pack('C').force_encoding('EUC-JP').encode('UTF-8').ord == b
end

jis0208 = plane([])
jis0212 = plane([0x8F])
seen = {}
[jis0208, jis0212].each do |rows|
  rows.join.each_char do |c|
    next if c == UNASSIGNED
    raise "code point U+#{c.ord.to_s(16)} appears twice" if seen[c]

    seen[c] = true
  end
end

assigned = ->(rows) { rows.join.count("^\0") }
output = <<~TS
  // SPDX-License-Identifier: MIT
  // Generated by scripts/gen-eucjp-table.rb (Ruby #{RUBY_VERSION}); do not edit.
  // Each string holds one JIS row of 94 cells (columns 0xA1..0xFE); "\\0" marks
  // an unassigned cell. JIS X 0208 has #{assigned.call(jis0208)} assigned cells,
  // JIS X 0212 has #{assigned.call(jis0212)}.

  /** Rows 0xA1..0xFE of the two-byte JIS X 0208 plane. */
  export const JIS0208_ROWS: readonly string[] = [
  #{jis0208.map { |row| literal(row) }.join("\n")}
  ];

  /** Rows 0xA1..0xFE of the three-byte (0x8F-prefixed) JIS X 0212 plane. */
  export const JIS0212_ROWS: readonly string[] = [
  #{jis0212.map { |row| literal(row) }.join("\n")}
  ];
TS

if ARGV.include?('--check')
  current = File.exist?(TARGET) ? File.read(TARGET, encoding: 'UTF-8') : ''
  if current == output
    puts 'eucjp-table: OK'
  else
    warn "eucjp-table: #{TARGET} differs from the generated table; run scripts/gen-eucjp-table.rb"
    exit 1
  end
else
  File.write(TARGET, output, encoding: 'UTF-8')
  puts "wrote #{TARGET}"
end
